export enum UserRole {
  MOH_ADMIN = 'MOH_ADMIN',
  WOREDA_ADMIN = 'WOREDA_ADMIN',
  HOSPITAL_ADMIN = 'HOSPITAL_ADMIN',
  DOCTOR = 'DOCTOR',
  NURSE = 'NURSE',
  DISPATCHER = 'DISPATCHER',
  MOTHER = 'MOTHER',
}
